/**
 * Discovery destination catalogue — filtering/scoring metadata only.
 * Place identity on selection is resolved through location intelligence.
 */

import type { BudgetLevel, TripCharacter, DiscoveryVibe } from './types';

export type DiscoveryCatalogueEntry = {
  id: string;
  /** Canonical name for LI resolveSync */
  placeName: string;
  displayName: string;
  countryCode: string;
  region: 'australia' | 'pacific' | 'asia' | 'other';
  iata?: string;
  characters: TripCharacter[];
  climate: Array<'tropical' | 'warm' | 'temperate' | 'cool'>;
  vibe: DiscoveryVibe;
  budgetLevel: BudgetLevel | 'flexible';
  /** Approximate nonstop / typical commercial flight hours from major AU hubs. */
  flightHoursFrom: Partial<Record<'SYD' | 'MEL' | 'BNE', number>>;
  activities: string[];
  familyFriendly: boolean;
  tags: string[];
};

export const DISCOVERY_CATALOGUE: DiscoveryCatalogueEntry[] = [
  {
    id: 'fiji-nadi',
    placeName: 'Fiji',
    displayName: 'Fiji',
    countryCode: 'FJ',
    region: 'pacific',
    iata: 'NAN',
    characters: ['tropical', 'beach', 'island', 'relaxation', 'romantic', 'family'],
    climate: ['tropical'],
    vibe: 'quiet',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 4.5, MEL: 5, BNE: 4 },
    activities: ['beach', 'snorkelling', 'kayaking', 'spa'],
    familyFriendly: true,
    tags: ['pacific', 'island'],
  },
  {
    id: 'vanuatu-vila',
    placeName: 'Vanuatu',
    displayName: 'Vanuatu',
    countryCode: 'VU',
    region: 'pacific',
    iata: 'VLI',
    characters: ['tropical', 'beach', 'island', 'relaxation', 'nature', 'adventure'],
    climate: ['tropical'],
    vibe: 'quiet',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 4, MEL: 4.5, BNE: 3.5 },
    activities: ['beach', 'snorkelling', 'diving', 'kayaking'],
    familyFriendly: true,
    tags: ['pacific', 'slower'],
  },
  {
    id: 'new-caledonia',
    placeName: 'New Caledonia',
    displayName: 'New Caledonia',
    countryCode: 'NC',
    region: 'pacific',
    iata: 'NOU',
    characters: ['tropical', 'beach', 'island', 'relaxation', 'cultural', 'food'],
    climate: ['tropical', 'warm'],
    vibe: 'mixed',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 3, MEL: 3.5, BNE: 2.5 },
    activities: ['beach', 'snorkelling', 'food'],
    familyFriendly: true,
    tags: ['pacific'],
  },
  {
    id: 'rarotonga',
    placeName: 'Rarotonga',
    displayName: 'Rarotonga',
    countryCode: 'CK',
    region: 'pacific',
    iata: 'RAR',
    characters: ['tropical', 'beach', 'island', 'relaxation', 'romantic'],
    climate: ['tropical'],
    vibe: 'quiet',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 6, MEL: 6.5, BNE: 5.5 },
    activities: ['beach', 'snorkelling', 'kayaking'],
    familyFriendly: true,
    tags: ['pacific', 'cook islands'],
  },
  {
    id: 'au-cairns',
    placeName: 'Cairns',
    displayName: 'Cairns',
    countryCode: 'AU',
    region: 'australia',
    iata: 'CNS',
    characters: ['tropical', 'beach', 'nature', 'adventure', 'family'],
    climate: ['tropical', 'warm'],
    vibe: 'mixed',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 3.5, MEL: 3.5, BNE: 2.5 },
    activities: ['reef', 'rainforest', 'kayaking', 'diving'],
    familyFriendly: true,
    tags: ['domestic', 'reef'],
  },
  {
    id: 'au-hamilton-island',
    placeName: 'Hamilton Island',
    displayName: 'Hamilton Island',
    countryCode: 'AU',
    region: 'australia',
    iata: 'HTI',
    characters: ['tropical', 'beach', 'island', 'relaxation', 'romantic', 'family'],
    climate: ['tropical', 'warm'],
    vibe: 'quiet',
    budgetLevel: 'luxury',
    flightHoursFrom: { SYD: 2.5, MEL: 3, BNE: 1.75 },
    activities: ['beach', 'snorkelling', 'sailing'],
    familyFriendly: true,
    tags: ['domestic', 'whitsundays'],
  },
  {
    id: 'au-noosa',
    placeName: 'Noosa',
    displayName: 'Noosa',
    countryCode: 'AU',
    region: 'australia',
    characters: ['beach', 'relaxation', 'food', 'nature', 'family'],
    climate: ['warm'],
    vibe: 'quiet',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 1.5, MEL: 2.25, BNE: 0.75 },
    activities: ['beach', 'kayaking', 'food', 'national park'],
    familyFriendly: true,
    tags: ['domestic'],
  },
  {
    id: 'au-byron',
    placeName: 'Byron Bay',
    displayName: 'Byron Bay',
    countryCode: 'AU',
    region: 'australia',
    characters: ['beach', 'relaxation', 'wellness', 'nature'],
    climate: ['warm'],
    vibe: 'mixed',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 1.25, MEL: 2, BNE: 0.75 },
    activities: ['beach', 'wellness', 'surfing'],
    familyFriendly: true,
    tags: ['domestic'],
  },
  {
    id: 'au-gold-coast',
    placeName: 'Gold Coast',
    displayName: 'Gold Coast',
    countryCode: 'AU',
    region: 'australia',
    iata: 'OOL',
    characters: ['beach', 'nightlife', 'family', 'city'],
    climate: ['warm'],
    vibe: 'lively',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 1.5, MEL: 2, BNE: 1 },
    activities: ['beach', 'theme parks', 'nightlife'],
    familyFriendly: true,
    tags: ['domestic'],
  },
  {
    id: 'id-bali',
    placeName: 'Bali',
    displayName: 'Bali',
    countryCode: 'ID',
    region: 'asia',
    iata: 'DPS',
    characters: ['tropical', 'beach', 'cultural', 'food', 'wellness', 'relaxation', 'nightlife'],
    climate: ['tropical'],
    vibe: 'mixed',
    budgetLevel: 'budget',
    flightHoursFrom: { SYD: 6.5, MEL: 6, BNE: 6 },
    activities: ['beach', 'temples', 'yoga', 'food', 'surfing'],
    familyFriendly: true,
    tags: ['asia'],
  },
  {
    id: 'th-phuket',
    placeName: 'Phuket',
    displayName: 'Phuket',
    countryCode: 'TH',
    region: 'asia',
    iata: 'HKT',
    characters: ['tropical', 'beach', 'nightlife', 'food', 'family'],
    climate: ['tropical'],
    vibe: 'lively',
    budgetLevel: 'budget',
    flightHoursFrom: { SYD: 9, MEL: 9, BNE: 8.5 },
    activities: ['beach', 'food', 'nightlife', 'snorkelling'],
    familyFriendly: true,
    tags: ['asia'],
  },
  {
    id: 'nz-queenstown',
    placeName: 'Queenstown',
    displayName: 'Queenstown',
    countryCode: 'NZ',
    region: 'other',
    iata: 'ZQN',
    characters: ['adventure', 'nature', 'snow', 'nightlife', 'food'],
    climate: ['cool', 'temperate'],
    vibe: 'lively',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 3, MEL: 3.5, BNE: 3.5 },
    activities: ['hiking', 'adventure', 'ski', 'food'],
    familyFriendly: true,
    tags: ['nz'],
  },
  {
    id: 'jp-tokyo',
    placeName: 'Tokyo',
    displayName: 'Tokyo',
    countryCode: 'JP',
    region: 'asia',
    iata: 'TYO',
    characters: ['city', 'cultural', 'food', 'nightlife', 'family'],
    climate: ['temperate'],
    vibe: 'lively',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 9.5, MEL: 10, BNE: 9 },
    activities: ['city', 'food', 'culture', 'shopping'],
    familyFriendly: true,
    tags: ['city-break'],
  },
  {
    id: 'sg-singapore',
    placeName: 'Singapore',
    displayName: 'Singapore',
    countryCode: 'SG',
    region: 'asia',
    iata: 'SIN',
    characters: ['city', 'food', 'cultural', 'family', 'nightlife'],
    climate: ['tropical', 'warm'],
    vibe: 'lively',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 8, MEL: 7.5, BNE: 7.5 },
    activities: ['city', 'food', 'family'],
    familyFriendly: true,
    tags: ['city-break'],
  },
  {
    id: 'au-melbourne',
    placeName: 'Melbourne',
    displayName: 'Melbourne',
    countryCode: 'AU',
    region: 'australia',
    iata: 'MEL',
    characters: ['city', 'cultural', 'food', 'nightlife'],
    climate: ['temperate'],
    vibe: 'lively',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 1.5, MEL: 0, BNE: 2.25 },
    activities: ['city', 'food', 'culture'],
    familyFriendly: true,
    tags: ['city-break', 'domestic'],
  },
  {
    id: 'au-sydney',
    placeName: 'Sydney',
    displayName: 'Sydney',
    countryCode: 'AU',
    region: 'australia',
    iata: 'SYD',
    characters: ['city', 'beach', 'cultural', 'food', 'nightlife', 'family'],
    climate: ['temperate', 'warm'],
    vibe: 'lively',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 0, MEL: 1.5, BNE: 1.5 },
    activities: ['city', 'beach', 'food'],
    familyFriendly: true,
    tags: ['city-break', 'domestic'],
  },
  {
    id: 'au-hobart',
    placeName: 'Hobart',
    displayName: 'Hobart',
    countryCode: 'AU',
    region: 'australia',
    iata: 'HBA',
    characters: ['city', 'nature', 'food', 'cultural', 'countryside'],
    climate: ['cool', 'temperate'],
    vibe: 'quiet',
    budgetLevel: 'mid_range',
    flightHoursFrom: { SYD: 2, MEL: 1.25, BNE: 2.75 },
    activities: ['food', 'nature', 'culture'],
    familyFriendly: true,
    tags: ['city-break', 'domestic'],
  },
];

export function catalogueById(id: string): DiscoveryCatalogueEntry | undefined {
  return DISCOVERY_CATALOGUE.find((e) => e.id === id);
}

export function catalogueByPlaceName(name: string): DiscoveryCatalogueEntry | undefined {
  const n = name.trim().toLowerCase();
  return DISCOVERY_CATALOGUE.find(
    (e) =>
      e.placeName.toLowerCase() === n ||
      e.displayName.toLowerCase() === n ||
      e.tags.some((t) => t === n),
  );
}
