/** Phase 1 — Aleya Intelligence Core: understand, remember, clarify. */

export type FieldSource = 'confirmed' | 'inferred';

export type FieldValue<T> = {
  value: T;
  source: FieldSource;
};

/** Phase 1 services only — schema stays extensible for later phases. */
export type TravelServiceKind =
  | 'flights'
  | 'accommodation'
  | 'car_hire'
  | 'transfers'
  | 'activities';

export type TripPurposeKind =
  | 'leisure'
  | 'business'
  | 'family'
  | 'romantic'
  | 'budget'
  | 'luxury'
  | 'other';

export type TimePreference = 'morning' | 'afternoon' | 'evening' | 'after_5pm' | 'flexible';

export type ApproximateDate = {
  kind: 'absolute' | 'relative' | 'month_end' | 'month_start' | 'weekend' | 'suggested';
  isoDate?: string;
  label: string;
  weekday?: number;
  month?: number;
  year?: number;
  timePreference?: TimePreference;
};

export type TravellerCounts = {
  adults: number;
  children: number;
  total: number;
};

export type BudgetValue = {
  amount?: number;
  currency?: string;
  style?: 'budget' | 'mid' | 'luxury';
};

export type ConversationState = {
  conversationId: string;
  origin?: FieldValue<string>;
  destination?: FieldValue<string>;
  departureDate?: FieldValue<ApproximateDate>;
  returnDate?: FieldValue<ApproximateDate>;
  departureTimePreference?: FieldValue<TimePreference>;
  returnTimePreference?: FieldValue<TimePreference>;
  requestedServices: TravelServiceKind[];
  accommodationArea?: FieldValue<string>;
  travellers?: FieldValue<TravellerCounts>;
  tripPurpose?: FieldValue<TripPurposeKind>;
  budget?: FieldValue<BudgetValue>;
  explicitItineraryIntent: boolean;
  missingRequiredFields: string[];
  lastSuggestedDate?: ApproximateDate;
  awaitingDateConfirmation: boolean;
  turnCount: number;
};

export type PipelineStage = 'understand' | 'extract' | 'infer' | 'store' | 'clarify' | 'continue';

export type IntelligenceResult = {
  stage: PipelineStage;
  state: ConversationState;
  reply: string;
  clarifications: string[];
  /** True only when the user explicitly asked for an itinerary. */
  explicitItineraryIntent: boolean;
  /** True only when an itinerary should be generated by a later phase/tool. */
  shouldGenerateItinerary: boolean;
  /** Always false in Phase 1 — no search tools are invoked. */
  searchPerformed: false;
};

export type ProcessMessageInput = {
  message: string;
  previousState?: ConversationState;
  now?: Date;
  travellerName?: string;
};

export function createEmptyConversationState(conversationId?: string): ConversationState {
  return {
    conversationId: conversationId ?? `conv-${Math.random().toString(36).slice(2, 10)}`,
    requestedServices: [],
    explicitItineraryIntent: false,
    missingRequiredFields: [],
    awaitingDateConfirmation: false,
    turnCount: 0,
  };
}
