/** Aleya Intelligence Layer — Phase 1 core + Phase 2 requirement intelligence. */

export type FieldSource = 'confirmed' | 'inferred';

/** Internal only — never surfaced in user-facing replies. */
export type ConfidenceLevel = 'high' | 'medium' | 'low';

export type FieldValue<T> = {
  value: T;
  source: FieldSource;
  /** 0–1 internal confidence score. */
  confidence?: number;
  confidenceLevel?: ConfidenceLevel;
};

/** Phase 1 services only — schema stays extensible for later phases. */
export type TravelServiceKind =
  | 'flights'
  | 'accommodation'
  | 'car_hire'
  | 'transfers'
  | 'activities';

export type TripPurposeKind =
  | 'leisure'
  | 'business'
  | 'family'
  | 'romantic'
  | 'budget'
  | 'luxury'
  | 'other';

export type TimePreference = 'morning' | 'afternoon' | 'evening' | 'after_5pm' | 'flexible';

export type ApproximateDate = {
  kind: 'absolute' | 'relative' | 'month_end' | 'month_start' | 'weekend' | 'suggested';
  isoDate?: string;
  label: string;
  weekday?: number;
  month?: number;
  year?: number;
  timePreference?: TimePreference;
};

export type TravellerCounts = {
  adults: number;
  children: number;
  infants: number;
  total: number;
};

export type BudgetValue = {
  amount?: number;
  currency?: string;
  style?: 'budget' | 'mid' | 'luxury';
  /** Relative adjuster from references like "cheaper". */
  relative?: 'cheaper' | 'more_expensive';
};

export type RoomRequirements = {
  rooms?: number;
  beds?: string;
  connecting?: boolean;
  notes?: string;
};

export type AirlinePreferences = {
  airlines?: string[];
  cabin?: string;
  directOnly?: boolean;
  notes?: string;
};

export type HotelPreferences = {
  stars?: number;
  brands?: string[];
  amenities?: string[];
  notes?: string;
};

export type RequirementConflict = {
  field: string;
  message: string;
  previousValue?: string;
  incomingValue?: string;
};

export type PresentedOption = {
  id: string;
  kind: 'flight' | 'hotel' | 'car' | 'transfer' | 'activity' | 'generic';
  label: string;
};

export type ReferenceResolution = {
  kind:
    | 'option_index'
    | 'same_hotel'
    | 'same_flights'
    | 'cheaper'
    | 'earlier'
    | 'later'
    | 'instead'
    | 'relative_date'
    | 'other';
  detail?: string;
  optionIndex?: number;
};

/** Compact intent summary for long conversations — structured state remains authoritative. */
export type ContextCompression = {
  summary: string;
  turnCountAtCompression: number;
  keyFacts: string[];
};

export type ConversationState = {
  conversationId: string;
  origin?: FieldValue<string>;
  destination?: FieldValue<string>;
  departureDate?: FieldValue<ApproximateDate>;
  returnDate?: FieldValue<ApproximateDate>;
  departureTimePreference?: FieldValue<TimePreference>;
  returnTimePreference?: FieldValue<TimePreference>;
  dateFlexibility?: FieldValue<'strict' | 'flexible' | 'plus_minus_days'>;
  requestedServices: TravelServiceKind[];
  accommodationArea?: FieldValue<string>;
  travellers?: FieldValue<TravellerCounts>;
  tripPurpose?: FieldValue<TripPurposeKind>;
  budget?: FieldValue<BudgetValue>;
  roomRequirements?: FieldValue<RoomRequirements>;
  airlinePreferences?: FieldValue<AirlinePreferences>;
  hotelPreferences?: FieldValue<HotelPreferences>;
  activities?: FieldValue<string[]>;
  dietaryRequirements?: FieldValue<string[]>;
  accessibility?: FieldValue<string[]>;
  loyaltyMemberships?: FieldValue<string[]>;
  specialRequests?: FieldValue<string[]>;
  transportNotes?: FieldValue<string>;
  explicitItineraryIntent: boolean;
  missingRequiredFields: string[];
  lastSuggestedDate?: ApproximateDate;
  awaitingDateConfirmation: boolean;
  turnCount: number;
  /** Active conflicts awaiting user resolution (Phase 2). */
  conflicts: RequirementConflict[];
  /** Last presented options for pronoun/reference resolution. */
  lastPresentedOptions: PresentedOption[];
  /** Selected option labels from references like "that one" / "first option". */
  selectedOptions: PresentedOption[];
  /** Internal compressed context for long chats. */
  contextCompression?: ContextCompression;
  /** Last applied reference resolution (internal). */
  lastReference?: ReferenceResolution;
  /** Fields updated on the most recent turn (internal). */
  lastUpdatedFields: string[];
};

export type PipelineStage = 'understand' | 'extract' | 'infer' | 'store' | 'clarify' | 'continue';

export type IntelligenceResult = {
  stage: PipelineStage;
  state: ConversationState;
  reply: string;
  clarifications: string[];
  /** True only when the user explicitly asked for an itinerary. */
  explicitItineraryIntent: boolean;
  /** True only when an itinerary should be generated by a later phase/tool. */
  shouldGenerateItinerary: boolean;
  /** Always false until a later phase invokes real search tools. */
  searchPerformed: false;
};

export type ProcessMessageInput = {
  message: string;
  previousState?: ConversationState;
  now?: Date;
  travellerName?: string;
  /** Optional options the UI presented (for "first option" / "that one"). */
  presentedOptions?: PresentedOption[];
};

export function createEmptyConversationState(conversationId?: string): ConversationState {
  return {
    conversationId: conversationId ?? `conv-${Math.random().toString(36).slice(2, 10)}`,
    requestedServices: [],
    explicitItineraryIntent: false,
    missingRequiredFields: [],
    awaitingDateConfirmation: false,
    turnCount: 0,
    conflicts: [],
    lastPresentedOptions: [],
    selectedOptions: [],
    lastUpdatedFields: [],
  };
}
